# main
FRAMES_PER_SECOND = 144
SCREEN_SIZE = (1280, 720)

# game mode
GAME_MODE_SCREEN_OFFSET = (300, 0)
GAME_MODE_SCREEN_SIZE = (SCREEN_SIZE[0] - GAME_MODE_SCREEN_OFFSET[0], SCREEN_SIZE[1] - GAME_MODE_SCREEN_OFFSET[1])
GRAPH_SCREEN_RELATIVE_OFFSET = (0, 185)
GRAPH_SCREEN_OFFSET = (GAME_MODE_SCREEN_OFFSET[0] + GRAPH_SCREEN_RELATIVE_OFFSET[0],
                       GAME_MODE_SCREEN_OFFSET[1] + GRAPH_SCREEN_RELATIVE_OFFSET[1])
GRAPH_SCREEN_SIZE = (SCREEN_SIZE[0] - GRAPH_SCREEN_OFFSET[0], SCREEN_SIZE[1] - GRAPH_SCREEN_OFFSET[1])

GRAPH_RELATIVE_OFFSET = (40, 40)
GRAPH_VERTEX_DISTANCE = 80
GRAPH_VERTEX_RADIUS = 10
GRAPH_GROUP_RADIUS = 20
GRAPH_GROUP_OVERSIZE = 20
