from utils import add_pos, sub_pos

# main
FRAMES_PER_SECOND = 144
SCREEN_SIZE = (1280, 720)
MENU_MARGIN = 50

# game mode
GAME_MODE_SCREEN_OFFSET = (300, 0)
GAME_MODE_HEAD_OFFSET = GAME_MODE_SCREEN_OFFSET
GAME_MODE_BODY_OFFSET = (300, 185)
GAME_MODE_MARGIN = 10

GAME_MODE_SCREEN_SIZE = sub_pos(SCREEN_SIZE, GAME_MODE_SCREEN_OFFSET)

GAME_MODE_HEAD_RELATIVE_OFFSET = sub_pos(GAME_MODE_HEAD_OFFSET, GAME_MODE_SCREEN_OFFSET)
GAME_MODE_HEAD_SIZE = (SCREEN_SIZE[0] - GAME_MODE_HEAD_OFFSET[0], GAME_MODE_BODY_OFFSET[1])

GAME_MODE_TEXT_BOX_SIZE = (round(GAME_MODE_HEAD_SIZE[0] * 0.66), round(GAME_MODE_HEAD_SIZE[1] * 0.9))

GAME_MODE_BODY_RELATIVE_OFFSET = sub_pos(GAME_MODE_BODY_OFFSET, GAME_MODE_SCREEN_OFFSET)
GAME_MODE_BODY_SIZE = sub_pos(SCREEN_SIZE, GAME_MODE_BODY_OFFSET)
GAME_MODE_BODY_MARGIN = 20

GRAPH_RELATIVE_OFFSET = (60, 60)
GRAPH_OFFSET = add_pos(GAME_MODE_BODY_OFFSET, GRAPH_RELATIVE_OFFSET)
GRAPH_VERTEX_DISTANCE_GRID = 100
GRAPH_VERTEX_RADIUS = 10
GRAPH_GROUP_RADIUS = 20
GRAPH_GROUP_OVERSIZE = 20
GRAPH_PENTAGRAM_RADIUS = 100
GRAPH_CUT_GAP = 10
GRAPH_CUT_LINE_POINT_DISTANCE = 5
